### ISSUE TITLE
Allow configuration of a base path

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#144]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Allow running Hub under arbitrary base URLs

### Motivation

I don't want to create a new domain for Hub, I want to serve it under a subresource of my existing domain.

To some extent, this can be done using a reverse proxy, however this only affects requests to the backend. The JS frontend deploys its own router, which is evaluated in the browser and thus not affected by my server-side proxy. Therefore a configuration value is required, which is available to both the Quarkus backend and Vue frontend.

### Considered Alternatives

Let the Vue router detect the current base path by reading `window.location`. However, this may cause _any_ path to be considered the base path, leading to infinite recursion in the router. The base path needs to be constant.

### Anything else?

This Traefik middleware has been used for testing whether one could reach the backend under arbitrary paths:

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /myCustomBasePath
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: strip-prefix@kubernetescrd
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /myCustomBasePath
            pathType: Prefix
            backend:
              service:
                name: cryptomator-hub-service
                port:
                  number: 8080
```
